'use strict';

module.exports =
  angular.module('stereoSelfie', [
    'ui.bootstrap',
    'ui.router',
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    'vid2d3d',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    // app
    require('./start').name,
    require('./capture').name,
    require('./results').name
  ])
  .config( /* @ngInject */
    function($compileProvider) {
      $compileProvider.aHrefSanitizationWhitelist(/^\s*(blob:|data:image)/);
    }
  )
